# Enable completion
autoload -U compinit
compinit

# Save a ton of history
HISTFILE=~/.zsh_history
HISTSIZE=20000
SAVEHIST=20000

# Add some PATH variables
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.bin/:$PATH
export PATH=$HOME/.cabal/bin/:$PATH
export PATH=./node_modules/.bin:$PATH

# Sourcing from other files
source $HOME/.zsh/aliases
source $HOME/.zsh/functions
source $HOME/.zsh/prompt

export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8
export EDITOR=nvim

# Enable vi-mode
bindkey -v
export KEYTIMEOUT=1

eval "$(rbenv init -)"
eval ~/.bin/base16-tomorrow-dark

export NVM_DIR="/Users/bzf/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
