#!/bin/sh

# Download vim-plug for neovim
if [ ! -e $HOME/.config/nvim/autoload/plug.vim ]; then
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install all plugins for neovim
nvim +PlugInstall +quit
