#! /bin/sh

PLATFORM=`uname -s`

# Platform specific values
if [ $PLATFORM = 'Linux' ]; then
  LS_COLOR='--color'
else
  LS_COLOR='-G'
fi

alias dots="cd $HOME/.dotfiles/"
alias l="ls -lh $LS_COLOR"
alias la="ls -lAh $LS_COLOR"
alias u='cd ..'
alias mkdir='mkdir -p'
alias powr='powder restart'
alias vim='nvim'
