#!/bin/zsh

function git_prompt {
  if $(git rev-parse --is-inside-work-tree 2>/dev/null); then
    branch=$(git symbolic-ref HEAD | cut -d'/' -f3- 2>/dev/null)
    echo " $branch"
  fi
}

function take {
  if [[ $# == 0 ]]; then
    echo "Usage: take <folder-name>"
  else
    mkdir -p $1;
    cd $1;
  fi
}

# g() is proudly stolen from thoughtbot/dotfiles
# No arguments: `git status`
# With arguments: acts like `git`
g() {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status
  fi
}

# Complete g like git
compdef g=git
